media:
  input: src/assets/images
  output: /_astro
content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/data/blog'
    view:
      fields: [ title, published, date ]
    fields:
      - name: draft
        label: Draft
        type: boolean
        default: true
      - name: pubDatetime
        label: Published date
        type: date
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text