services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:80
    restart: unless-stopped
    # No need for volumes in production as content is baked into the image
